#!/bin/bash
# Atlas macOS Application Bundling Script
# This script creates a standalone macOS application bundle (.app)

# Exit on error
set -e

# Directory of this script
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Check for required tools
if ! command -v python3 &> /dev/null; then
    echo "Error: Python 3 is required but not found"
    exit 1
fi

if ! command -v pip3 &> /dev/null; then
    echo "Error: pip3 is required but not found"
    exit 1
fi

# Ensure py2app is installed
if ! python3 -c "import py2app" &> /dev/null; then
    echo "Installing py2app..."
    pip3 install py2app
fi

# Ensure dmgbuild is installed
if ! command -v dmgbuild &> /dev/null; then
    echo "Installing dmgbuild..."
    pip3 install dmgbuild
fi

# Check for icon file
if [ ! -f "assets/icon.icns" ]; then
    echo "Warning: Icon file 'assets/icon.icns' not found"
    echo "Using default icon"
fi

# Create setup.py for py2app if it doesn't exist
if [ ! -f "setup.py" ]; then
    echo "Creating setup.py for py2app..."
    cat > setup.py << EOL
"""
This is a setup.py script generated by py2app specifically for
building the Atlas macOS application.
"""

from setuptools import setup

APP = ['app/main.py']
DATA_FILES = [
    ('', ['requirements.txt']),
    ('assets', ['assets/icon.icns', 'assets/icon.png']),
    ('config', ['config/config-macos.ini', 'config/default.json']),
]
OPTIONS = {
    'argv_emulation': True,
    'packages': [
        'atlas',
        'utils',
        'ui',
        'core',
        'tools',
    ],
    'iconfile': 'assets/icon.icns',
    'plist': {
        'CFBundleName': 'Atlas',
        'CFBundleDisplayName': 'Atlas',
        'CFBundleIdentifier': 'com.your-org.atlas',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'NSHumanReadableCopyright': 'Copyright © 2025 Your Organization',
        'NSHighResolutionCapable': True,
    },
    'includes': [
        'PySide6',
        'numpy',
        'pandas',
        'openai',
        'langchain',
    ],
}

setup(
    name='Atlas',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
EOL
fi

# Clean previous build if exists
echo "Cleaning previous build..."
rm -rf build dist

# Build the application
echo "Building macOS application bundle..."
python3 setup.py py2app

# Create a DMG installer if dmgbuild is available
if command -v dmgbuild &> /dev/null; then
    echo "Creating DMG installer..."
    
    # Create DMG settings file
    cat > dmg-settings.py << EOL
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import biplist
import os.path

# Application name
application = defines.get('app', 'Atlas.app')
appname = os.path.basename(application)

# Volume format
format = defines.get('format', 'UDBZ')

# Volume size
size = defines.get('size', None)

# Files to include
files = [application]

# Symlinks to create
symlinks = {'Applications': '/Applications'}

# Volume icon
icon = 'assets/icon.icns'

# Icon locations
icon_locations = {
    appname: (140, 120),
    'Applications': (500, 120)
}

# Window settings
window_rect = ((100, 100), (640, 280))
background = 'builtin-arrow'

# DMG settings
show_status_bar = False
show_tab_view = False
show_toolbar = False
show_pathbar = False
show_sidebar = False
sidebar_width = 180
EOL
    
    # Create DMG
    dmgbuild -s dmg-settings.py "Atlas" "dist/Atlas.dmg"
    
    echo "DMG installer created at: dist/Atlas.dmg"
else
    echo "dmgbuild not found, skipping DMG creation."
fi

echo "Build completed successfully!"
echo "Application bundle available at: dist/Atlas.app"
