#!/usr/bin/env python3
"""Створює __init__.py файли в усіх необхідних директоріях проекту."""
import os
import logging

def create_init_files():
    """Створює __init__.py файли в усіх необхідних директоріях проекту."""
    # Налаштування логування
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    logger = logging.getLogger(__name__)

    # Отримання поточного каталогу
    project_root = os.getcwd()
    
    # Список каталогів, які слід проігнорувати
    ignore_dirs = {
        '.git', 'venv', '__pycache__', 'env', 'node_modules', 
        'backup_archive', 'backup_ui', 'legacy-tests', 'unused',
        'profiling_output', 'test_temp_generated_tools', 'performance_reports'
    }
    
    # Обхід усіх каталогів у проекті
    for root, dirs, files in os.walk(project_root):
        # Видалення ігнорованих каталогів зі списку для обходу
        dirs[:] = [d for d in dirs if d not in ignore_dirs]
        
        # Якщо це не кореневий каталог проекту
        if root != project_root:
            init_file_path = os.path.join(root, '__init__.py')
            
            # Створення __init__.py, якщо його немає
            if not os.path.exists(init_file_path):
                try:
                    with open(init_file_path, 'w') as f:
                        f.write("""# This file marks the directory as a Python package.
# It's automatically generated by create_init_files.py script.
""")
                    logger.info(f'Створено __init__.py в {root}')
                except Exception as e:
                    logger.error(f'Не вдалося створити __init__.py в {root}: {str(e)}')

if __name__ == '__main__':
    create_init_files()