#!/usr/bin/env python3
"""Ініціалізує git-репозиторій з правильною конфігурацією."""

import logging
import os
import subprocess


def init_git_repo():
    """Ініціалізує git-репозиторій з правильною конфігурацією."""
    # Налаштування логування
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
    )
    logger = logging.getLogger(__name__)

    try:
        # Перевірка, чи вже ініціалізовано git-репозиторій
        if os.path.exists(".git"):
            logger.info("Git-репозиторій вже ініціалізований")
            return

        # Ініціалізація git-репозиторія
        subprocess.run(["git", "init"], check=True)
        logger.info("Git-репозиторій успішно ініціалізований")

        # Налаштування git-config
        subprocess.run(["git", "config", "user.name", '"NIMDA Developer"'], check=True)
        subprocess.run(["git", "config", "user.email", '"dev@nimda.local"'], check=True)
        subprocess.run(["git", "config", "core.editor", '"nano"'], check=True)
        subprocess.run(["git", "config", "pull.rebase", "false"], check=True)
        logger.info("Git-конфігурація виконана")

        # Додавання .gitignore, якщо його немає
        if not os.path.exists(".gitignore"):
            with open(".gitignore", "w") as f:
                f.write(
                    "# See https://www.git-scm.com/docs/gitignore for more details about git ignore files\n"
                )
                f.write("# This file is generated by init_git_repo.py script\n\n")
                f.write("# Ignore Python build artifacts\n")
                f.write("/__pycache__/\n")
                f.write("*.pyc\n")
                f.write("*.pyo\n")
                f.write("*.pyd\n\n")
                f.write("# Ignore macOS specific files\n")
                f.write(".DS_Store\n")
                f.write(".AppleDouble\n")
                f.write(".LSOverride\n\n")
                f.write("# Ignore virtual environments\n")
                f.write("venv/\n")
                f.write("env/\n")
                f.write(".env/\n")
                f.write(".venv/\n")
                f.write("ENV/\n")
                f.write("env.bak/\n")
                f.write("venv.bak/\n")
            logger.info("Створено базовий .gitignore файл")

        # Додавання файлів до git
        subprocess.run(["git", "add", "."], check=True)
        logger.info("Усі файли додані до git")

        # Створення першого коміту
        subprocess.run(
            ["git", "commit", "-m", '"Initial commit from NIMDA Atlas"'], check=True
        )
        logger.info("Перший коміт створено")

        # Виведення інструкцій для користувача
        logger.info("")
        logger.info(
            "Готово! Тепер ви можете додати віддалений репозиторій та виконати пуш:"
        )
        logger.info("1. Створіть порожній репозиторій на GitHub/GitLab тощо")
        logger.info("2. Виконайте команду: git remote add origin <your-repo-url>")
        logger.info("3. Виконайте команду: git branch -M main")
        logger.info("4. Виконайте команду: git push -u origin main")

    except subprocess.CalledProcessError as e:
        logger.error(f"Помилка під час ініціалізації git-репозиторія: {str(e)}")


if __name__ == "__main__":
    init_git_repo()
